import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Home from '../Components/Dashboard/Home'
import { useSelector } from 'react-redux'
export default function Index() {
  const show  = useSelector(state=> state.info.users)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        {show? (
        <div className={styles.dark}>
            <Home />
        </div> ) : (
        <div className={styles.light}>
          <Home />
        </div> )}
        
          
       
      

      
    </div>
  )
}
